#Hello this plugin is made by OnlineMetlesley.
#Autorespawn set to true to enable it, then setup the message and time in seconds.
#KickonDeath set to true to enable it, then setup the command 
#If you have any questions or bug reports, please join our discord. https://discord.gg/xAHP8cA

version:
  #Disallow /version
  Enabled: true
  #What Message should the plugin send when the player tried to execute it?
  BlockMessage: '&cYou are not allowed to use that command!'
  #Should the plugin save the player who executed the command in the player.yml?
  SavePlayer: true
  Broadcast: true
  BroadcastMessage: '&b%player% tried to use /version'

plugins:
  #Disallow /plugins
  Enabled: true
  #What Message should the plugin send when the player tried to execute it?
  BlockMessage: '&cYou are not allowed to use that command!'
  #Should the plugin save the player who executed the command in the player.yml?
  SavePlayer: true
  Broadcast: true
  BroadcastMessage: '&b%player% tried to use /plugins'
  
ver:
  #Disallow /ver
  Enabled: true
  #What Message should the plugin send when the player tried to execute it?
  BlockMessage: '&cYou are not allowed to use that command!'
  #Should the plugin save the player who executed the command in the player.yml?
  SavePlayer: true
  Broadcast: true
  BroadcastMessage: '&b%player% tried to use /ver'
  
pl:
  #Disallow /pl
  Enabled: true
  #What Message should the plugin send when the player tried to execute it?
  BlockMessage: '&cYou are not allowed to use that command!'
  #Should the plugin save the player who executed the command in the player.yml?
  SavePlayer: true
  Broadcast: true
  BroadcastMessage: '&b%player% tried to use /pl'

questionmark:
  #Disallow /?
  Enabled: true
  #What Message should the plugin send when the player tried to execute it?
  BlockMessage: '&cYou are not allowed to use that command!'
  #Should the plugin save the player who executed the command in the player.yml?
  SavePlayer: true
  Broadcast: true
  BroadcastMessage: '&b%player% tried to use /?'
  
about:
  #Disallow /about
  Enabled: true
  #What Message should the plugin send when the player tried to execute it?
  BlockMessage: '&cYou are not allowed to use that command!'
  #Should the plugin save the player who executed the command in the player.yml?
  SavePlayer: true
  Broadcast: true
  BroadcastMessage: '&b%player% tried to use /about'

icanhasbukkit:
  #Disallow /icanhasbukkit
  Enabled: true
  #What Message should the plugin send when the player tried to execute it?
  BlockMessage: '&cYou are not allowed to use that command!'
  #Should the plugin save the player who executed the command in the player.yml?
  SavePlayer: true
  Broadcast: true
  BroadcastMessage: '&b%player% tried to use /icanhasbukkit'

bukkitver:
  #Disallow /bukkit:ver
  Enabled: true
  #What Message should the plugin send when the player tried to execute it?
  BlockMessage: '&cYou are not allowed to use that command!'
  #Should the plugin save the player who executed the command in the player.yml?
  SavePlayer: true
  Broadcast: true
  BroadcastMessage: '&b%player% tried to use /bukkit:ver'

bukkitplugins:
  #Disallow /bukkit:plugins
  Enabled: true
  #What Message should the plugin send when the player tried to execute it?
  BlockMessage: '&cYou are not allowed to use that command!'
  #Should the plugin save the player who executed the command in the player.yml?
  SavePlayer: true
  Broadcast: true
  BroadcastMessage: '&b%player% tried to use /bukkit:plugins'

bukkitversion:
  #Disallow /bukkit:versions
  Enabled: true
  #What Message should the plugin send when the player tried to execute it?
  BlockMessage: '&cYou are not allowed to use that command!'
  #Should the plugin save the player who executed the command in the player.yml?
  SavePlayer: true
  Broadcast: true
  BroadcastMessage: '&b%player% tried to use /bukkit:version'

bukkithelp:
  #Disallow /bukkit:help
  Enabled: true
  #What Message should the plugin send when the player tried to execute it?
  BlockMessage: '&cYou are not allowed to use that command!'
  #Should the plugin save the player who executed the command in the player.yml?
  SavePlayer: true
  Broadcast: true
  BroadcastMessage: '&b%player% tried to use /bukkit:help'

bukkitabout:
  #Disallow /bukkit:about
  Enabled: true
  #What Message should the plugin send when the player tried to execute it?
  BlockMessage: '&cYou are not allowed to use that command!'
  #Should the plugin save the player who executed the command in the player.yml?
  SavePlayer: true
  Broadcast: true
  BroadcastMessage: '&b%player% tried to use /bukkit:about'

bukkitquestionmark:
  #Disallow /bukkit:?
  Enabled: true
  #What Message should the plugin send when the player tried to execute it?
  BlockMessage: '&cYou are not allowed to use that command!'
  #Should the plugin save the player who executed the command in the player.yml?
  SavePlayer: true
  Broadcast: true
  BroadcastMessage: '&b%player% tried to use /bukkit:?'

bukkitpl:
  #Disallow /bukkit:pl
  Enabled: true
  #What Message should the plugin send when the player tried to execute it?
  BlockMessage: '&cYou are not allowed to use that command!'
  #Should the plugin save the player who executed the command in the player.yml?
  SavePlayer: true
  Broadcast: true
  BroadcastMessage: '&b%player% tried to use /bukkit:pl'
